global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'lstm-dashboard-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'lstm-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['lstm-app:8099']
    scrape_interval: 10s
    scrape_timeout: 5s
